#If for some reason you want to disable this plugin, just set this to 'false'. Default: true.
enable-plugin: true

#INTERNAL languages available: portuguese, english. Default: english
language: english

#Should administrators be warned about new updates? Default: true.
#If 'true', this will not bother you while you are playing. I promisse!
update:
    check: true

#Do not change this under any circumstances!
config-version: 1