name: WhereAreYou
description: A tool to helps OPs on finding players current locations in Minecraft 1.13.x.
version: 0.1.0
api-version: 1.13
load: STARTUP
author: [leothawne]
website: https://leothawne.github.io/WhereAreYou/
url: https://leothawne.github.io/WhereAreYou/
main: io.github.leothawne.WhereAreYou.WhereAreYou
database: false
commands:
    whereareyou:
        description: A Where Are You command.
        aliases: [wru]
        usage: /<command>
    whereareyouadmin:
        description: A Where Are You command.
        aliases: [wrua]
        usage: /<command>
permissions:
    WhereAreYou.use:
        description: A Where Are You permission node.
        default: true
    WhereAreYou.admin:
        description: A Where Are You permission node.
        default: op