name: WhereAreYou
description: Simple tool to help you to find your friends easier.
version: 0.1.0
api-version: 1.13
load: STARTUP
author: [leothawne]
website: https://leothawne.github.io/WhereAreYou/
url: https://leothawne.github.io/WhereAreYou/
main: io.github.leothawne.WhereAreYou.WhereAreYouLoader
database: false
commands:
    whereareyou:
        description: All available commands for Where Are You.
        aliases: [wru]
        usage: /<command>
    whereareyouadmin:
        description: All admin commands for Where Are You.
        aliases: [wrua]
        usage: /<command>
permissions:
    WhereAreYou.use:
        description: Allow players to use WRU commands.
        default: true
    WhereAreYou.find:
        description: Allow players to find other players' locations.
        default: true
    WhereAreYou.admin:
        description: Allow admins to use WRU admin commands.
        default: op